### ISSUE TITLE
kamloops node school international

### ISSUE THREAD

**Issue by jonotron** [nodeschool/kamloops#2]
## Details

**Date**: Saturday May 23rd, 1-4pm
**Venue**: TRUSU Board room???? or KIC co-working?
### Mentors
- [ ] @chadfawcett 
- [ ] @jonotron
- [ ] @dchymko
- [ ] @hevets
### Event day details
- [ ] snacks
- [ ] drinks
- [ ] stickers

I'd like to keep this free like last time, and maybe encourage folks to kick in some cash to cover cost of snacks and drinks.

First question: should we use TRUSU boardroom (assuming it's available) or KIC Co-working. I'm tempted to use TRUSU for the accessibility and table access. Amanda can book for us if this makes sense.

Thoughts?

**Comment by chadfawcett** [comment]
I would say if there are going to be as many people as last year, then it would be better to book the TRUSU boardroom. It'll be a familiar place for the students that can attend.

KIC would be a great place if there is 12 people or less attending.

**Comment by iancrowther** [comment]
is this event still happening?

**Comment by jonotron** [comment]
@iancrowther Yes, we are just sorting out a venue before getting a registration link up.

**Comment by iancrowther** [comment]
ok, can you update the schedule pls :-)

**Comment by iancrowther** [comment]
ok great, just add a link to the event page when your done

**Comment by jonotron** [comment]
Event signup page: https://www.picatic.com/nodeschoolintlkamloops

**Comment by chrisfosterelli** [comment]
Can't make it this time, but hope it is awesome!

**Comment by hevets** [comment]
Unfortunately I'll also be unable to attend due to prior commitments :crying_cat_face:

Have a blast!
