### ISSUE TITLE
do you have a chapter logo?

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/kamloops#3]
can you add any international day assets to https://drive.google.com/folderview?id=0B1E3fBFiidMXS2txV0N2ejVKNjg&usp=sharing

**Comment by jonotron** [comment]
@iancrowther looks like someone has already uploaded the assets. Thanks mysterious and helpful person.

Unfortunately, we do not yet have a chapter logo. I'm hoping to have one by next international day, but definitely not in time for this video production.

**Comment by iancrowther** [comment]
yeah it was me :-)
